version: '3'
services:
  redis-server:         #this name is used as reference in Node-server to link between theese two.
    image: 'redis' 
  node-app:
    restart: always     #restart policy when container with this service crashes
    build: ./           #builds Node server image from Dockerfile at this path
    ports:
      - "3001:3001"     # localhost : port inside containers

# EXECUTION COMMAND
# docker-compose up --build
# build flag -> if any changes are made.
# -d flag -> to run in background.